apiVersion: v1
kind: Service
metadata:
  name: gfs-master
  namespace: default
spec:
  type: ClusterIP
  selector:
    app: gfs-master
  ports:
    - name: grpc
      port: 50051
      targetPort: 50051
