apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "gfs.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "gfs.labels" . | nindent 4 }}
data:
  GFS_REPLICATION_FACTOR: {{ .Values.cluster.replicationFactor | quote }}
  GFS_LEASE_DURATION_SECS: {{ .Values.cluster.leaseDurationSecs | quote }}
  GFS_HEARTBEAT_INTERVAL_SECS: {{ .Values.cluster.heartbeatIntervalSecs | quote }}
  GFS_SCRUB_INTERVAL_SECS: {{ .Values.cluster.scrubIntervalSecs | quote }}
  GFS_MASTER_OPLOG_PATH: {{ .Values.cluster.oplogPath | quote }}
