{{- if .Values.rbac.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "gfs.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "gfs.labels" . | nindent 4 }}
{{- end }}
